services:
  - type: web
    name: prokrishi-frontend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: prokrishi-server # This must match your backend service name
          envVarKey: URL
      - key: NEXT_PUBLIC_FACEBOOK_APP_ID
        sync: false
      - key: PORT
        value: 3000
      - key: GENERATE_SOURCEMAP
        value: false