services:
  - type: static_site
    name: prokrishi-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: out
    headers:
      - path: "/*"
        name: "X-Frame-Options"
        value: "DENY"
      - path: "/*"
        name: "X-Content-Type-Options"
        value: "nosniff"
    routes:
      - type: rewrite
        source: "/:path*"
        destination: "/:path*.html"
      - type: rewrite
        source: "/"
        destination: "/index.html"
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false # Set this in the Render dashboard
      - key: NEXT_PUBLIC_FACEBOOK_APP_ID
        sync: false # Set this in the Render dashboard
      - key: GENERATE_SOURCEMAP
        value: false 